# Generated by Django 4.2.2 on 2023-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Profile photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Remaining balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
