# Generated by Django 4.2.2 on 2023-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, null=True, verbose_name='Verification code'),
        ),
    ]
