# Generated by Django 4.2.2 on 2023-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
