# Generated by Django 4.2.2 on 2023-06-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_username_alter_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
